### ISSUE TITLE
xorgxrdp segfaults Xorg on reconnect: OsLookupColor+0x139

### ISSUE THREAD

**Issue by nobias** [neutrinolabs/xrdp#1367]
I experienced two crashes within the past month when trying to reconnect to an Xrdp session that had been running for many days/weeks, with many successful reconnects. One day however, upon reconnect, my remote desktop client showed a black screen. I wouldn't be able to say what was different in the failed reconnect attempts (in contrast to all the successful ones before). After closing the client window and another connection retry, a fresh desktop is spawned, and all open apps from the previous session are lost. 

The relevant ~/.xorgxrdp.?.log log file contains the following error:
```
[2168320.699] rdpRROutputGetProperty:
[2168320.726] (EE)
[2168320.726] (EE) Backtrace:
[2168320.728] (EE) 0: /usr/lib/xorg/Xorg (OsLookupColor+0x139) [0x559c10550459]
[2168320.735] (EE) 1: /lib/x86_64-linux-gnu/libpthread.so.0 (funlockfile+0x50) [0x7fbff07358df]
[2168320.743] (EE) 2: /usr/lib/xorg/modules/libxorgxrdp.so (a8r8g8b8_to_a8b8g8r8_box+0xd7) [0x7fbff3281da7]
[2168320.746] (EE) 3: /usr/lib/xorg/modules/libxorgxrdp.so (rdpCapture+0xb7b) [0x7fbff3282c8b]
[2168320.749] (EE) 4: /usr/lib/xorg/modules/libxorgxrdp.so (rdpClientConEndUpdate+0x145) [0x7fbff327fbd5]
[2168320.752] (EE) 5: /usr/lib/xorg/modules/libxorgxrdp.so (rdpClientConGetScreenImageRect+0x30c) [0x7fbff32815dc]
[2168320.752] (EE) 6: /usr/lib/xorg/Xorg (TimerSet+0x180) [0x559c10549d50]
[2168320.752] (EE) 7: /usr/lib/xorg/Xorg (TimerSet+0x1e7) [0x559c10549e07]
[2168320.752] (EE) 8: /usr/lib/xorg/Xorg (WaitForSomething+0x277) [0x559c10549ef7]
[2168320.752] (EE) 9: /usr/lib/xorg/Xorg (SendErrorToClient+0x113) [0x559c103f3243]
[2168320.752] (EE) 10: /usr/lib/xorg/Xorg (InitFonts+0x3c8) [0x559c103f7478]
[2168320.755] (EE) 11: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xe7) [0x7fbff0353b97]
[2168320.755] (EE) 12: /usr/lib/xorg/Xorg (_start+0x2a) [0x559c103e113a]
[2168320.755] (EE)
[2168320.755] (EE) Segmentation fault at address 0xffffffffffffffff
[2168320.755] (EE)
Fatal server error:
[2168320.755] (EE) Caught signal 11 (Segmentation fault). Server aborting
```

Both times, I was running Matlab R2019a in the crashed session, as well as standard Ubuntu apps (terminal, file browser) and the Fiji/ImageJ image analysis software (Java-based). Either Matlab (the GUI of which is based on Java AWT) or Fiji/ImageJ also leave behind a crash log file that contains the following:
```
FATAL ERROR in native method: Nativewindow X11 IOError: Display 0x7fbd343d2a30 (:10.0): Resource temporarily unavailable
        at sun.awt.X11.XlibWrapper.XEventsQueued(Native Method)
        at sun.awt.X11.XToolkit.run(XToolkit.java:566)
        at sun.awt.X11.XToolkit.run(XToolkit.java:532)
        at java.lang.Thread.run(Thread.java:748)
```

I'm running packages xrdp 0.9.5-2 and xorgxrdp 0.2.6-1build1 on an up-to-date Ubuntu 18.04 LTS. I'm using MS Remote Desktop Client 10.2.13 (1593) to connect from MacOS 10.14.5. The client was configured for 2450 x 1340 px, 16 bit color, clipboard and sound forwarding, in a non-fullscreen window. 

I'm attaching my relevant snippets from my /var/log/xrdp.log, /var/log/xrdp-sesman.log, as well as ~/.xorgxrdp.10.log and ~/.xsession-errors (slightly redacted for privacy). Timestamp of crash: July 5, 14h44: [xorgxrdp.10.log.txt](https://github.com/neutrinolabs/xrdp/files/3363885/xorgxrdp.10.log.txt), [xrdp-sesman.log.txt](https://github.com/neutrinolabs/xrdp/files/3363886/xrdp-sesman.log.txt), [xrdp.log.txt](https://github.com/neutrinolabs/xrdp/files/3363887/xrdp.log.txt), [xsession-errors.txt](https://github.com/neutrinolabs/xrdp/files/3363888/xsession-errors.txt)

The only related issue I was able to find is #447. In contrast to what is reported there, I definitely did not alter the original xrdp.ini from the package.

Any hints appreciated! Please let me know if I can provide further debugging information. Thank you.

**Comment by bantu** [comment]
I believe to also see this issue after upgrading to Debian 10 (Buster).

**Comment by metalefty** [comment]
@bantu What about Buster clean installation?

**Comment by bantu** [comment]
@metalefty I am afraid, I will not be performing a clean install of Debian 10. Anything else I can look out for in particular?

**Comment by metalefty** [comment]
This is actually xorgxrdp issue, not xrdp. See neutrinolabs/xorgxrdp#121.

**Comment by bantu** [comment]
For the record: I purged and reinstalled the xrdp package, then customized the xrdp.ini to my use case. This solved the problem for me.
