### ISSUE TITLE
Cannot use "neutrirdp-any" for proxy connection

### ISSUE THREAD

**Issue by Mr-LZG** [neutrinolabs/xrdp#1573]
platform 
```
centos7.5
Linux devplat7 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

xrdp version
```
xrdp-0.9.13
```

Neutriordp version
```
cNeutrinoRDP-devel （Current latest version）
```

build NeutrinoRdp
```
    cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .
    make
    sudo make install
```
build xrdp
```
    ./bootstrap
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
    ./configure --enable-neutrinordp
    make
    make install
```

xrdp.log
```
[20200508-17:36:39] [INFO ] Socket 12: AF_INET connection received from 172.16.162.1 port 46251
[20200508-17:36:39] [DEBUG] Closed socket 12 (AF_INET 172.16.99.28:3389)
[20200508-17:36:39] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)
[20200508-17:36:39] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20200508-17:36:39] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20200508-17:36:39] [DEBUG] Security layer: requested 11, selected 0
[20200508-17:36:39] [DEBUG] Closed socket 12 (AF_INET 172.16.99.28:3389)
[20200508-17:36:46] [INFO ] Socket 12: AF_INET connection received from 172.16.162.1 port 46253
[20200508-17:36:46] [DEBUG] Closed socket 12 (AF_INET 172.16.99.28:3389)
[20200508-17:36:46] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)
[20200508-17:36:46] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20200508-17:36:46] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20200508-17:36:46] [DEBUG] Security layer: requested 0, selected 0
[20200508-17:36:46] [INFO ] connected client computer name: LZG-PC
[20200508-17:36:46] [INFO ] all channels are disabled by configuration
[20200508-17:36:46] [INFO ] Non-TLS connection established from 172.16.162.1 port 46253: encrypted with standard RDP security
[20200508-17:36:46] [DEBUG] xrdp_00001f06_wm_login_mode_event_00000001
[20200508-17:36:46] [INFO ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20200508-17:36:46] [INFO ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20200508-17:36:46] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20200508-17:36:46] [WARN ] local keymap file for 0x00000804 found and doesn't match built in keymap, using local keymap file
```

![image](https://user-images.githubusercontent.com/22317592/81365150-fa6ed980-9119-11ea-9d32-aca18a0d2445.png)

Can anyone help me, thanks！

**Comment by metalefty** [comment]
Can you change the system locale to English and show the message in the last screenshot?

**Comment by Mr-LZG** [comment]
Hi @metalefty , this is a screenshot of the English prompt
![image](https://user-images.githubusercontent.com/22317592/81377780-c1922d00-9138-11ea-9425-662d1ae4aa0a.png)

**Comment by Mr-LZG** [comment]
Hi @metalefty ,I debug xrdp and get a Segmentation fault
```
    1535   instance->settings->bitmap_cache = 1;
    1536   instance->settings->bitmapCacheV2NumCells = 3; // 5;
    1537   instance->settings->bitmapCacheV2CellInfo[0].numEntries = 600; // 0x78;
    1538   instance->settings->bitmapCacheV2CellInfo[0].persistent = 0;
```
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fce59a2fee1 in lfreerdp_pre_connect (instance=0x20d3e20) at xrdp-neutrinordp.c:1537
1537	    instance->settings->bitmapCacheV2CellInfo[0].numEntries = 600; // 0x78;
(gdb) bt
#0  0x00007fce59a2fee1 in lfreerdp_pre_connect (instance=0x20d3e20) at xrdp-neutrinordp.c:1537
#1  0x00007fce640442b9 in freerdp_connect () from /lib64/libfreerdp-core.so.1.0
#2  0x00007fce59a2d18a in lxrdp_connect (mod=0x24c7360) at xrdp-neutrinordp.c:102
#3  0x00000000004156bf in xrdp_mm_setup_mod2 (self=0x1fdb930, guid=0x0) at xrdp_mm.c:583
#4  0x000000000041925b in xrdp_mm_connect (self=0x1fdb930) at xrdp_mm.c:2339
#5  0x000000000042450e in xrdp_wm_login_mode_changed (self=0x1fd6f10) at xrdp_wm.c:1969
#6  0x0000000000424d69 in xrdp_wm_check_wait_objs (self=0x1fd6f10) at xrdp_wm.c:2214
#7  0x000000000041eb53 in xrdp_process_main_loop (self=0x1f7d8d0) at xrdp_process.c:282
#8  0x000000000040f3e6 in xrdp_process_run (in_val=0x0) at xrdp_listen.c:151
#9  0x000000000041079d in xrdp_listen_fork (self=0x1f7d930, server_trans=0x1f74740) at xrdp_listen.c:803
#10 0x0000000000410b67 in xrdp_listen_main_loop (self=0x1f7d930) at xrdp_listen.c:952
#11 0x000000000040647a in main (argc=1, argv=0x7ffd4e01d908) at xrdp.c:679
(gdb) p instance->settings->bitmapCacheV2CellInfo
$13 = (BITMAP_CACHE_V2_CELL_INFO *) 0x0

```

**Comment by Mr-LZG** [comment]
Sorry!
 I just found that there is an old version of freerdp in my machine, and xrdp is connected to the old version of freerdp. Remove the old version of freerdp, and recompile Neutriordp and xrdp have solved the problem.
