### ISSUE TITLE
lock problem

### ISSUE THREAD

**Issue by moobyfr** [neutrinolabs/xrdp#175]
I'm facing a recurrent problem on xrdp
the xrdp-sesman stop working
the backtrace seems explain why it's locked:
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f1fab3a0657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f1fab3a0480 in __GI___pthread_mutex_lock (mutex=0x25e5d30) at ../nptl/pthread_mutex_lock.c:79
#3  0x00007f1fab9d9aa9 in tc_mutex_lock (mutex=<optimized out>) at thread_calls.c:130
#4  0x000000000040679c in lock_chain_acquire () at lock.c:57
#5  0x0000000000405cfc in session_kill (pid=24900) at session.c:925
#6  <signal handler called>
#7  0x00007f1fab3a535d in write () at ../sysdeps/unix/syscall-template.S:81
#8  0x00007f1fab9d7fec in g_file_write (fd=<optimized out>,

```
ptr=ptr@entry=0x7fff9b6f11c0 "[20141002-10:57:58] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 9\n", len=<optimized out>)
at os_calls.c:1862
```
#9  0x00007f1fab9d63ab in log_message (lvl=lvl@entry=LOG_LEVEL_INFO, msg=msg@entry=0x7f1fab9dc2a8 "An established connection closed to endpoint: %s") at log.c:609
#10 0x00007f1fab9d7563 in g_tcp_close (sck=sck@entry=9) at os_calls.c:674
#11 0x00000000004049e2 in x_server_running_check_ports (display=13) at session.c:220
#12 session_get_aval_display_from_chain () at session.c:402
#13 session_start_fork (width=1680, height=1050, bpp=24, username=0x7f1fa416f350 "hiertz", password=0xXXXXXXXX "XXXXXXXXX", data=XXXXXXX, type=3 '\003',

```
program=0x0, directory=0x0, client_ip=0x7f1fa41641f0 "192.168.85.49:33417 - socket: 8", domain=<optimized out>) at session.c:506
```
#14 0x0000000000405c5a in session_sync_start () at session.c:901
#15 0x0000000000403569 in sesman_main_loop () at sesman.c:100
#16 main (argc=<optimized out>, argv=<optimized out>) at sesman.c:393

It causes the user being unable to start again a session

**Comment by moobyfr** [comment]
we didn't face these issues this year, assuming fixed.
